language: node_js
sudo: true
install:
- sudo apt-get install libtool
- sudo apt-get install automake
- sudo apt-get install autoconf
- npm install
node_js:
  - 10
cache:
  directories:
    - "node_modules"
after_success:
  - npm install -g codecov
  - codecov